-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Error exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


intro : Translations -> String -> String
intro translations caller =
    tr translations Curly "Error.intro" [ ( "caller", caller ) ]
