-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Error exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


intro : Translations -> String
intro translations =
    t translations "Error.intro"


errorMsg : Translations -> String -> String
errorMsg translations msg =
    tr translations Curly "Error.errorMsg" [ ( "msg", msg ) ]


errorContent : Translations -> String -> String
errorContent translations msg =
    tr translations Curly "Error.errorContent" [ ( "msg", msg ) ]


errorTimestamp : Translations -> String
errorTimestamp translations =
    t translations "Error.errorTimestamp"
