-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Home exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


title : Translations -> String
title translations =
    t translations "Home.title"


yourPreferredLang : Translations -> String -> String
yourPreferredLang translations lang =
    tr translations Curly "Home.yourPreferredLang" [ ( "lang", lang ) ]
