-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Lang exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


german : Translations -> String
german translations =
    t translations "Lang.german"


english : Translations -> String
english translations =
    t translations "Lang.english"
