-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Login exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


title : Translations -> String
title translations =
    t translations "Login.title"


message : Translations -> String
message translations =
    t translations "Login.message"


username : Translations -> String
username translations =
    t translations "Login.username"


password : Translations -> String
password translations =
    t translations "Login.password"


login : Translations -> String
login translations =
    t translations "Login.login"


loggingIn : Translations -> String
loggingIn translations =
    t translations "Login.loggingIn"
