-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Message exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


empty : Translations -> String
empty translations =
    t translations "Message.empty"


logoffTitle : Translations -> String
logoffTitle translations =
    t translations "Message.logoffTitle"


logoffSuccess : Translations -> String
logoffSuccess translations =
    t translations "Message.logoffSuccess"
