-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.NotFound exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


title : Translations -> String
title translations =
    t translations "NotFound.title"


message : Translations -> String
message translations =
    t translations "NotFound.message"
