-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Page exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


notLoggedInText : Translations -> String
notLoggedInText translations =
    t translations "Page.notLoggedInText"


loggedInText : Translations -> String -> String
loggedInText translations name =
    tr translations Curly "Page.loggedInText" [ ( "name", name ) ]


logoutTooltip : Translations -> String
logoutTooltip translations =
    t translations "Page.logoutTooltip"


success : Translations -> String
success translations =
    t translations "Page.success"


info : Translations -> String
info translations =
    t translations "Page.info"


warning : Translations -> String
warning translations =
    t translations "Page.warning"


error : Translations -> String
error translations =
    t translations "Page.error"
