-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Route exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


privacy : Translations -> String
privacy translations =
    t translations "Route.Privacy"


imprint : Translations -> String
imprint translations =
    t translations "Route.Imprint"
